name: statsforecast
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - prophet
  - pip
  - scipy
  - statsmodels
  - tabulate
  - pip:
    - nbdev
