name: statsforecast
channels:
  - conda-forge
dependencies:
  - coreforecast>=0.0.7
  - holidays<0.21 # zone info errors
  - jupyterlab
  - matplotlib
  - numba>=0.55.0
  - numpy>=1.21.6
  - pandas>=1.3.5,<2.2
  - pyspark>=3.3
  - pip
  - prophet
  - pyarrow
  - scikit-learn
  - scipy>=1.7.3
  - statsmodels>=0.13.2
  - tabulate
  - threadpoolctl
  - plotly
  - utilsforecast>=0.1.4
  - pip:
    - datasetsforecast
    - fugue[dask,ray]
    - nbdev
    - plotly-resampler
    - polars
    - supersmoother
    - tqdm
