name: statsforecast
channels:
  - conda-forge
dependencies:
  - coreforecast>=0.0.7
  - jupyterlab
  - matplotlib
  - numba>=0.55.0
  - numpy>=1.21.6,<2
  - pandas>=1.3.5
  - pip
  - prophet
  - pyarrow
  - scikit-learn
  - scipy>=1.7.3
  - statsmodels>=0.13.2
  - tabulate
  - threadpoolctl
  - plotly
  - pip:
    - datasetsforecast
    - nbdev
    - plotly-resampler
    - polars
    - supersmoother
    - tqdm
    - utilsforecast>=0.1.4
