project:
  type: website

format:
  html:
    theme: cosmo
    fontsize: 1em
    linestretch: 1.7
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  google-analytics: "G-NXJNCVR18L"
  repo-actions: [issue]
  favicon: favicon_png.png
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Get Started"
        href: examples/Getting_Started_short.ipynb
      - text: "NixtlaVerse"
        menu:
          - text: "MLForecast 🤖"
            href: https://github.com/nixtla/statsforecast/issues/new/choose
          - text: "NeuralForecast 🧠"
            href: https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A
          - text: "HierarchicalForecast 👑"
            href: https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A
          
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/nixtla/statsforecast/issues/new/choose
          - text: "Join our Slack"
            icon: chat-right-text
            href: https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A
    right:
      - icon: github
        href: "https://github.com/nixtla/statsforecast"
      - icon: twitter
        href: https://twitter.com/nixtlainc
        aria-label: Nixtla Twitter

  sidebar:
    style: floating
  body-footer: |
    Give us a ⭐ on [Github](https://github.com/nixtla/stats)

metadata-files: [nbdev.yml, sidebar.yml]
