name: "build-docs"
on:
  push:
    branches: ["mintlify"]
  workflow_dispatch:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install Dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -Uq nbdev
          test -f setup.py && pip install -e ".[dev]"
          nbdev_docs
      - name: Copy over navigation.json
        run: |
          cp nbs/navigation.json _docs/navigation.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: docs
          publish_dir: ./_docs
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `docs` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
